//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrandedKart.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public short Postal { get; set; }
        public string Country { get; set; }
        public int AddressId { get; set; }
        public int orderId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
